MACOSX_DEPLOYMENT_TARGET:
- '10.9'
VERBOSE_AT:
- V=1
VERBOSE_CM:
- VERBOSE=1
arpack:
- '3.5'
blas_impl:
- openblas
- mkl
boost:
- '1.65'
bzip2:
- '1.0'
c_compiler:
- vs2015
cairo:
- '1.14'
cpu_optimization_target:
- nocona
cross_compiler_target_platform:
- win-32
- win-64
curl:
- '7.54'
cxx_compiler:
- vs2015
dbus:
- '1'
expat:
- '2.2'
ffmpeg:
- 3.2.3
flann:
- 1.9.1
fontconfig:
- '2.12'
fortran_compiler:
- intel-fortran
fortran_compiler_version:
- 16.0.4
freetype:
- '2.8'
geos:
- 3.6.2
giflib:
- '5.1'
glib:
- '2.53'
glpk:
- '4.62'
gmp:
- '6.1'
gst_plugins_base:
- '1.12'
gstreamer:
- '1.12'
harfbuzz:
- '1.7'
hdf4:
- '4.2'
hdf5:
- '1.10'
icu:
- '58'
ignore_build_only_deps:
- python
ipython:
- '6.1'
jpeg:
- '9'
json_c:
- '0.12'
krb5:
- '1.14'
libblitz:
- '0.10'
libdap4:
- '3.19'
libevent:
- 2.0.22
libffi:
- '3.2'
libgdal:
- '2.2'
libiconv:
- '1.15'
libkml:
- '1.3'
libmatio:
- '1.5'
libnetcdf:
- '4.4'
libpng:
- '1.6'
librdkafka:
- 0.9.5
libssh2:
- '1.8'
libsvm:
- '3.21'
libtiff:
- '4.0'
libwebp:
- '0.5'
libxml2:
- '2.9'
lua:
- '5'
lzo:
- '2'
macos_machine:
- x86_64-apple-darwin13.4.0
macos_min_version:
- '10.9'
metis:
- '5.1'
mkl:
- '2018'
mpfr:
- '3'
ncurses:
- '5.9'
netcdf_cxx4:
- '4.3'
netcdf_fortran:
- '4.4'
nettle:
- '3.3'
numpy:
- '1.11'
openblas:
- 0.2.20
openjpeg:
- '2.3'
openssl:
- 1.0.2
pango:
- '1.40'
perl:
- '5.26'
pin_run_as_build:
  libboost:
    max_pin: x.x
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    max_pin: x.x.x
    min_pin: x.x.x
pixman:
- '0.34'
poppler:
- '0.61'
proj4:
- '4'
protobuf:
- '3.4'
pyqt:
- '5.6'
python:
- '3.6'
qt:
- '5.6'
r_base:
- '3.4'
readline:
- '7'
scipy:
- '0.19'
snappy:
- '1'
sox:
- '14.4'
sqlite:
- '3'
sundials:
- '2.7'
target_platform:
- win-64
tk:
- '8.6'
vc:
- '14'
vlfeat:
- '0.9'
xerces_c:
- '3'
xz:
- '5'
zeromq:
- '4.2'
zip_keys:
- - python
  - ipython
  - vc
  - c_compiler
  - cxx_compiler
  - fortran_compiler_version
- - pyqt
  - qt
zlib:
- '1.2'
